"""Constants for Duco component for ESPHome."""

CONF_CPU_TEMPERATURE = "cpu_temperature"
CONF_HASHRATE = "hashrate"
CONF_ACCEPTED_SHARES = "accepted_shares"
CONF_TOTAL_SHARES = "total_shares"
CONF_DIFFICULTY = "difficulty"
CONF_SHARE_RATE = "share_rate"
CONF_ACCEPTED_RATE = "accept_rate"
CONF_PING = "ping"
CONF_CORES_STATUS = "cores_status"
CONF_POOL = "pool"

UNIT_KILO_HASH_PER_SECOND = "KH/s"

ICON_SPEEDOMETER = "mdi:speedometer"
ICON_CHART_ARC = "mdi:chart-arc"
ICON_TROPHY_AWARD = "mdi:trophy-award"
ICON_POUND_BOX = "mdi:pound-box-outline"
ICON_VECTOR_DIFFERENCE = "mdi:vector-difference"
ICON_PUZZLE = "mdi:puzzle"
ICON_MINECRAFT = "mdi:minecraft"
ICON_CPU = "mdi:cpu-64-bit"
ICON_WEB = "mdi:web"
