text:
  - platform: template
    name: "Username"
    id: duco_username_text
    optimistic: true
    min_length: 0
    max_length: 32
    mode: text
    restore_value: true
    icon: "mdi:account"
    entity_category: config
    disabled_by_default: true
    web_server:
      sorting_group_id: duco_group
      sorting_weight: 0
    on_value:
      then:
        - lambda: |-
            id(miner).sync_web_config(id(duco_username_text).state, id(duco_key_text).state, id(duco_worker_text).state);

  - platform: template
    name: "Miner Key"
    id: duco_key_text
    optimistic: true
    min_length: 0
    max_length: 64
    mode: text
    restore_value: true
    icon: "mdi:key-chain-variant"
    entity_category: config
    disabled_by_default: true
    web_server:
      sorting_group_id: duco_group
      sorting_weight: 1
    on_value:
      then:
        - lambda: |-
            id(miner).sync_web_config(id(duco_username_text).state, id(duco_key_text).state, id(duco_worker_text).state);

  - platform: template
    name: "Miner Name"
    id: duco_worker_text
    optimistic: true
    min_length: 0
    max_length: 32
    mode: text
    restore_value: true
    icon: "mdi:cpu"
    entity_category: config
    disabled_by_default: true
    web_server:
      sorting_group_id: duco_group
      sorting_weight: 2
    on_value:
      then:
        - lambda: |-
            id(miner).sync_web_config(id(duco_username_text).state, id(duco_key_text).state, id(duco_worker_text).state);

esphome:
  on_boot:
    - priority: 500.0
      then:
        - delay: 5s
        - lambda: |-
            id(miner).sync_web_config(id(duco_username_text).state, id(duco_key_text).state, id(duco_worker_text).state);
