substitutions:
  comment: "ESPHome DucoMiner | ESP8266"

wifi:
  min_auth_mode: WPA2

http_request:
  useragent: "esphome/${name} (${project_version})"
  verify_ssl: false
  tls_buffer_size_rx: 16384
  timeout: 10s
